# Generated by Django 5.1.4 on 2026-01-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('iata', models.CharField(max_length=4)),
                ('icao', models.CharField(max_length=4)),
            ],
        ),
    ]
