# Generated by Django 5.0.6 on 2025-01-02 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threadly', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id']},
        ),
    ]
