# Generated by Django 5.0.6 on 2025-01-02 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_alter_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id']},
        ),
    ]
